import Head from "next/head";
import Link from "next/link";

import type { GetServerSideProps, NextPage } from "next";
import { getServerAuthSession } from "@/server/auth";
import { buttonVariants } from "@/components/ui/button";

const Landing: NextPage = () => {
  return (
    <div className="relative min-h-screen bg-black bg-gradient-to-tr from-zinc-900/50 to-zinc-700/30">
      <Head>
        <title>Brainwave</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-8 pb-8 md:gap-16 md:pb-16 xl:pb-24">
        <div className="mx-auto mt-8 flex max-w-3xl flex-col items-center justify-center px-8 sm:mt-0 sm:min-h-screen sm:px-0">
          <div className="hidden sm:mb-8 sm:flex sm:justify-center">
            <Link
              href="/auth/sign-in"
              className="relative overflow-hidden rounded-full px-4 py-1.5 text-sm leading-6 text-zinc-400 ring-1 ring-zinc-100/10 duration-150 hover:ring-zinc-100/30"
            >
              Ignite your{" "}
              <span className="font-semibold text-zinc-200">
                Intelligence
                <span className="ml-2" aria-hidden="true">
                  &rarr;
                </span>
              </span>
            </Link>
          </div>
          <div>
            <h1 className="bg-gradient-to-t from-zinc-100/50 to-white bg-clip-text py-4 text-center text-5xl font-bold tracking-tight text-transparent sm:text-7xl">
              AI SAT Prep
            </h1>
            <p className="mt-6 leading-5 text-zinc-600 sm:text-center">
              Introducing Brainwave: the ultimate quiz platform for learners. Take quizzes
              on your favorite subjects, at your desired difficulty level. Build
              your knowledge and earn badges to showcase your skills. Brainwave
              is the perfect tool for studying for the SAT.
            </p>
            <div className="mx-auto mt-8 flex flex-col justify-center gap-4 sm:max-w-lg sm:flex-row ">
              <Link
                href="/auth/sign-in"
                className={buttonVariants({
                  variant: "default",
                  size: "lg",
                })}
              >
                Get Started
              </Link>
              {/* <Link
                href="/share"
                className="hover:drop-shadow-cta inline-block space-x-2 rounded bg-zinc-50  px-4 py-1.5 text-base font-semibold leading-7 text-zinc-800 ring-1 ring-transparent   transition-all duration-150 hover:bg-zinc-900/20 hover:text-zinc-100 hover:ring-zinc-600/80  sm:w-1/2 sm:text-center md:py-2"
              >
                <span>How it Works</span>
                <span aria-hidden="true">&rarr;</span>
              </Link> */}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession(context);
  if (session) {
    return {
      redirect: {
        destination: "/home",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};

export default Landing;
